export PATH="/Applications/Vagrant/bin/:$PATH"
export ANDROID_HOME="/Users/tim/android-sdk-macosx"
export PYTHONPATH=$(brew --prefix)/lib/python2.7/site-packages
export PATH=/usr/local/go/bin:$PATH
export PATH=/usr/local/sbt/bin:$PATH
export PATH="/Applications/Postgres.app/Contents/MacOS/bin:$PATH"
export PATH="/Users/tim/Library/Application Support/Titanium/mobilesdk/osx/2.1.4.GA:$PATH"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="./bin:$PATH"
export PATH="/Users/tim/dev/depot_tools:$PATH"
export PATH="/Applications/git-annex.app/Contents/MacOS:$PATH"
export PATH="/Users/tim/android-sdk-macosx/tools:/Users/tim/android-sdk-macosx/platform-tools:$PATH"
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11/bin:$PATH
export EDITOR="/usr/local/bin/mvim"
export LC_CTYPE="utf-8"
export PATH="$PATH:/Applications/Emacs.app/Contents/MacOS/bin"
export PATH="$PATH:/usr/local/share/npm/bin"
export GOPATH=$HOME/go
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home
